import assert from "node:assert/strict"
import { describe, it } from "node:test"
import { createCopyPreview, createStableCopyIntent } from "./copy-preview.ts"
import { OrganizationIdSchema, ShopIdSchema } from "./model.ts"
import { PostgresCopyPreviewRepository } from "./postgres-copy-preview.ts"
import { FakeCopyPreviewPostgresExecutor } from "./postgres-copy-preview.fake.ts"
import { readFileSync } from "node:fs"
const organizationId=OrganizationIdSchema.parse("10000000-0000-4000-8000-000000000001"); const shopId=ShopIdSchema.parse("30000000-0000-4000-8000-000000000001")
const preview=createCopyPreview({ source:{ organizationId, sourceShopId: shopId, sourceProductId:"p-1", capturedAt:"2026-09-09T00:00:00.000Z", completeness:"complete", title:"Product", description:"Description", categoryId:"cat", attributes:{ color:"red" } }, requirement:{ organizationId, destinationShopId:shopId, capturedAt:"2026-09-09T00:00:00.000Z", completeness:"complete", allowedCategoryIds:["cat"], requiredAttributes:["color"], maximumTitleLength:100 }, mapping:{ destinationCategoryId:"cat" } }); const intent=createStableCopyIntent(preview)
describe("PostgreSQL copy-preview persistence contract",()=>{ it("round-trips immutable intent and valid preview",async()=>{const repo=new PostgresCopyPreviewRepository(new FakeCopyPreviewPostgresExecutor()); await repo.save({intent,preview}); const read=await repo.read({organizationId,destinationShopId:shopId},intent.copyIntentId); assert.equal(read?.intent.activePreviewHash,preview.previewHash); assert.equal(read?.preview.kind,"valid")}); it("keeps shop scope fail closed",async()=>{const repo=new PostgresCopyPreviewRepository(new FakeCopyPreviewPostgresExecutor()); await repo.save({intent,preview}); assert.equal(await repo.read({organizationId,destinationShopId:ShopIdSchema.parse("30000000-0000-4000-8000-000000000009")},intent.copyIntentId),null)}); it("keeps migration organization/shop FKs and no secrets",()=>{const sql=readFileSync(new URL("../../../db/migrations/0008_copy_preview.sql",import.meta.url),"utf8"); assert.match(sql,/FOREIGN KEY \(organization_id, destination_shop_id, active_preview_hash\)/); assert.match(sql,/UNIQUE \(organization_id, destination_shop_id, preview_hash\)/); assert.doesNotMatch(sql,/access_token|refresh_token|callback_code|authorization_header/i)})})
